version: "3"
services:
  runner:
    # build: . # If you want to Build the Image locally (You need the complete Repo on your PC)
    image: buddyspencer/gickup:latest
    volumes:
      - ${PWD}/conf.yml:/gickup/conf.yml
    command: ["./gickup/app", "/gickup/conf.yml"]
